### ISSUE TITLE
good ad on!

### ISSUE THREAD

**Issue by finvontel** [justverifyit/thunderbird#24]
Do I have to start the scan by clicking the "just verify" button in the message or can the ad-on scan attachments automatically without being started manually?

**Comment by nicprov** [comment]
@finvontel Unfortunately you need to click the "Verify It" button for it to verify an email. This for a few reasons:

1. Your API key is very limited (4 lookups / min), so you will very quickly get rate-limited by VirusTotal.
2. You wouldn't want to upload all attachments to VirusTotal because they would have a copy (especially sensitive documents).
3. Running it in the background in permanence with Thunderbird could cause a serious slowdown.

Having said all that, if your main concern is having to wait for an email to process, what you can do is click the "Verify It" button, then move on to other messages. When you come back to that message after a few minutes, you can click the button again, and you will get your result instantly, this is because the result will be cached.
